### ISSUE TITLE
Community meeting reminder - Thursday, January 5 at 20:00 UTC

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/community#19]
A reminder that we have a scheduled GeoPandas community meeting this Thursday, January 5 at 20:00 UTC (moved here from the last Thursday of December).

Tentative agenda and notes (feel free to add points ahead of the meeting): https://hackmd.io/pq8MqmtxTFqqaiayFuuEYQ

Link to the Zoom meeting: https://us06web.zoom.us/j/88360697466?pwd=ZXlxSXd6WWI2bEoxS2ZzbjZSa3d5Zz09

As always, we welcome not only the @geopandas/collaborators but everyone willing to spend some time talking about GeoPandas (and related packages) and its future. Also, feel free to join as observers only.

**Comment by jorisvandenbossche** [comment]
Also cc @benbovy and @thomcom (and colleagues) in case you are interested

**Comment by thomcom** [comment]
Thanks for the ping @jorisvandenbossche !
