### ISSUE TITLE
Community Meeting - March 25, 2021

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/community#2]
Tomorrow, Thursday 25 at 17:30 UTC, we have a dev call. All welcome to join!

Meeting link: https://liverpool-ac-uk.zoom.us/j/99068468774?pwd=WkoyVFJIS2s2ejBSMDNyNlR2aVFDUT09
Meeting notes: https://hackmd.io/pq8MqmtxTFqqaiayFuuEYQ

**Comment by martinfleis** [comment]
cc @sangarshanan you may be interested ;).
