### ISSUE TITLE
Community meeting reminder - Thursday January 26 at 17:00 UTC

### ISSUE THREAD

**Issue by brendan-ward** [geopandas/community#20]
Tentative agenda and notes (feel free to add points ahead of the meeting): https://hackmd.io/pq8MqmtxTFqqaiayFuuEYQ

Link to the Zoom meeting: https://us06web.zoom.us/j/88360697466?pwd=ZXlxSXd6WWI2bEoxS2ZzbjZSa3d5Zz09

As always, we welcome not only the @geopandas/collaborators  but everyone willing to spend some time talking about GeoPandas (and related packages) and its future. Also, feel free to join as observers only.

-- 
prior posting:
This is currently on the GeoPandas calendar but not yet on the list of upcoming meetings #12 (probably needs a new issue for 2023).

**Comment by martinfleis** [comment]
Yeah, schedule in #12 is not up to date. I believe we have a call tomorrow as scheduled.
