### ISSUE TITLE
Community meeting reminder - Thursday September 30, 17:00 UTC

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/community#5]
As a reminder we have our bi-monthly meeting this week Thursday at 17:00 UTC (see https://github.com/geopandas/community/issues/3)

* Agenda / notes: https://hackmd.io/pq8MqmtxTFqqaiayFuuEYQ
* Google Meet link: meet.google.com/zrc-tscs-oha

And cc-ing some recent active contributors (@m-richards, @adriangb,@gcarcia, @andreaseliasson, @mesejo, @TLouf, @Imanflow), obviously no obligation at all, but just to make you aware of this meeting (and this repo). In case you would be interested in joining, you are certainly welcome!

**Comment by jorisvandenbossche** [comment]
@martinfleis hmm, I just notice that the calendar item for Thursday says 18:00 for me, which actually corresponds to 16:00 UTC and not 17:00 UTC ?

**Comment by martinfleis** [comment]
Have I messed the time zones again? July was at the same time. Shall I fix the calendar to make it 17:00 UTC?

**Comment by Imanflow** [comment]
I'll join, I looked forward to get closer contact.

**Comment by martinfleis** [comment]
The calendar is fixed now (I hope).

If anyone wants to subscribe to it, the link is here https://calendar.google.com/calendar/u/0?cid=MjhhbTQzczBjdnRldm9sdjg4YnJybTE2Z29AZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ

**Comment by jorisvandenbossche** [comment]
cc @gcaria (had your github handle wrong in the top post)

**Comment by jorisvandenbossche** [comment]
@martinfleis thanks!

**Comment by TLouf** [comment]
I'll join too, thanks for the invitation :)

**Comment by jorisvandenbossche** [comment]
I created the https://github.com/geopandas/benchmarks repo. Feel free to open issues with ideas for good datasets (with a short description of the dataset, link to where it can be found, etc. Or even some code if you already used the dataset yourself).

**Comment by m-richards** [comment]
Thanks also for the invititation! I'm glad to see these kind of community meetings happen, but the timing doesn't really work in my time zone

**Comment by martinfleis** [comment]
@m-richards Which time zone are you in?

**Comment by m-richards** [comment]
> @m-richards Which time zone are you in?

AEST / UTC+10, so the meeting was 3am 😅. It makes sense though that you pick a time working for the US & Europe as I'd imagine that covers the vast majority of contributors - I don't mind missing it that much either.
