### ISSUE TITLE
Community meeting reminder - Thursday December 02, 17:00 UTC 

### ISSUE THREAD

**Issue by martinfleis** [geopandas/community#8]
A reminder that we have a scheduled GeoPandas community meeting this Thursday, December 02, at 17:00 UTC.

- Tentative agenda (will be filled ahead of the meeting): https://hackmd.io/pq8MqmtxTFqqaiayFuuEYQ
- Link to the Zoom meeting: https://us06web.zoom.us/j/88360697466?pwd=ZXlxSXd6WWI2bEoxS2ZzbjZSa3d5Zz09

As always, we welcome not only the @geopandas/collaborators but everyone willing to spend some time talking about GeoPandas and its future. Also, feel free to join as observers only.

A ping to recently active contributors who may be interested (I know that some of you are in unfriendly time zones, sorry). @m-richards, @adriangb, @gcaria, @andreaseliasson, @mesejo, @TLouf, @Imanflow, @simberaj, @snowman2. Do not feel any obligation to join, I just wanted to ensure you are aware in case you are interested.

**Comment by snowman2** [comment]
Thanks for the ping :+1:. I have a meeting conflict at that time, but will plan to join if it ends early. Either way, I would be interested in joining future meetings.

**Comment by martinfleis** [comment]
@snowman2 I am going to update #3 after the meeting with a schedule for 2022 but you can also subscribe to the shared calendar if that helps (https://calendar.google.com/calendar/embed?src=28am43s0cvtevolv88brrm16go%40group.calendar.google.com&ctz=Europe%2FLondon).

**Comment by martinfleis** [comment]
also cc @benbovy

**Comment by jorisvandenbossche** [comment]
Just a note that I updated the meeting link to a Zoom one: https://us06web.zoom.us/j/88360697466?pwd=ZXlxSXd6WWI2bEoxS2ZzbjZSa3d5Zz09

**Comment by jorisvandenbossche** [comment]
Opened a new issue for the next meeting tomorrow: https://github.com/geopandas/community/issues/9
